language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

install:
  # The setuptools on some travis containers are too old, need to manually upgrade
  - pip install --upgrade setuptools
  - pip install -e .[test]

script:
  - py.test
  - flake8 .
